package com.example.data

import android.content.Context
import com.example.data.api.CivicApi
import com.example.data.api.ReportDto
import com.example.data.api.RetrofitClient
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import java.io.IOException

class ReportRepository(private val context: Context) {
    private val database = AppDatabase.getDatabase(context)
    private val dao = database.reportDao()

    // Single source of truth from Room DB
    val reportsFlow: Flow<List<ReportEntity>> = dao.getAllReportsFlow()

    // Get API instance dynamically based on current settings preferences
    private fun getApi(): CivicApi = RetrofitClient.getApi(context)

    suspend fun getLocalReports(): List<ReportEntity> = withContext(Dispatchers.IO) {
        dao.getAllReports()
    }

    /**
     * GET: Fetches reports from server and caches them locally (offline cache)
     */
    suspend fun refreshReports(): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            val api = getApi()
            val remoteDtos = api.getReports()
            
            // Map remote DTOs to synchronized local entities
            val localEntities = remoteDtos.map { dto ->
                dto.toEntity(isSynced = true)
            }
            
            // Update cache (for simplified lab, insert all, overriding old entries)
            if (localEntities.isNotEmpty()) {
                dao.insertReports(localEntities)
            }
            Result.success(Unit)
        } catch (e: Exception) {
            // Fails gracefully (no internet or server down) - local DB ensures offline functionality
            Result.failure(e)
        }
    }

    /**
     * POST: Adds a new report. Saves locally first, then attempts to POST to the server.
     */
    suspend fun createReport(
        title: String,
        description: String,
        category: String,
        severity: String,
        sender: String,
        lat: Double,
        lng: Double,
        light: Float,
        battery: Int
    ): Result<ReportEntity> = withContext(Dispatchers.IO) {
        val tempId = 0 // Auto-generated by Room
        val report = ReportEntity(
            title = title,
            description = description,
            category = category,
            severity = severity,
            sender = sender,
            latitude = lat,
            longitude = lng,
            ambientLight = light,
            batteryLevel = battery,
            isSynced = false // Unsynced initially
        )

        // 1. Insert locally in Room
        val insertedId = dao.insertReport(report).toInt()
        val savedReport = report.copy(id = insertedId)

        // 2. Attempt to upload to Tomcat Servlet server via POST
        try {
            val api = getApi()
            val dto = ReportDto.fromEntity(savedReport)
            val returnedDto = api.submitReport(dto)
            
            // 3. If online upload succeeds, update reports to mark as Synced in Local Database
            dao.markSynced(insertedId)
            Result.success(savedReport.copy(isSynced = true))
        } catch (e: Exception) {
            // Fails: stays archived locally as unsynced
            Result.success(savedReport)
        }
    }

    /**
     * Syncs any reports that were created while offline (queued in local Room DB)
     */
    suspend fun syncOfflineReports(): Int = withContext(Dispatchers.IO) {
        val unsynced = dao.getUnsyncedReports()
        var syncCount = 0
        if (unsynced.isEmpty()) return@withContext 0

        val api = getApi()
        for (report in unsynced) {
            try {
                val dto = ReportDto.fromEntity(report)
                api.submitReport(dto)
                dao.markSynced(report.id)
                syncCount++
            } catch (e: Exception) {
                // Ignore failure for individual items and keep trying others, or stop
                break
            }
        }
        syncCount
    }

    suspend fun clearCache() = withContext(Dispatchers.IO) {
        dao.clearAll()
    }

    suspend fun deleteReport(id: Int) = withContext(Dispatchers.IO) {
        dao.deleteReportById(id)
    }
}
